- name: Get docker package.
  hosts: localhost
  tasks:
    - name: Check the directory target exists before install docker
      stat:
        path: "{{ docker_path }}"
      register: stat_docker

    - name: Create docker path folder
      file:
        path: "{{ docker_path }}"
        state: directory
        mode: u=rwX,g=rX,o=rX
      when: stat_docker.stat.exists == false

    - name: Check the directory target exists before install dependencies
      stat:
        path: "{{ dependencies_path }}"
      register: stat_dependencies

    - name: Create dependencies path folder
      file:
        path: "{{ dependencies_path }}"
        state: directory
        mode: u=rwX,g=rX,o=rX
      when: stat_dependencies.stat.exists == false

    - name: Check the directory target exists before install docker-compose
      stat:
        path: "{{ docker_compose_path }}"
      register: stat_docker_compose

    - name: Create docker-compose path folder
      file:
        path: "{{ docker_compose_path }}"
        state: directory
        mode: u=rwX,g=rX,o=rX
      when: stat_docker_compose.stat.exists == false

    - name: Install docker package # if this failed, try "ansible-playbook -c local local.yml"
      get_url:
        url: "https://download.docker.com/linux/centos/7/x86_64/stable/Packages/{{ docker_version }}"
        dest: "{{ docker_path }}"

    - name: Install dependencies
      get_url:
        url: " {{ item }} "
        dest: "{{ dependencies_path }}"
      with_items: "{{ dependencies }}"
      when:
        - dependencies is defined

    - name: Ensure docker-compose is installed and available
      get_url: 
        url : https://github.com/docker/compose/releases/download/1.22.0/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}
        dest: "{{ docker_compose_path }}"
        mode: 'u+x,g+x'

    - name: Make sure docker-compose file name
      shell: "mv `ls {{ docker_compose_path }} | grep docker-compose` docker-compose"
      args:
        chdir: "{{ docker_compose_path }}"
      ignore_errors: True
